name = "quickstage-web"
compatibility_date = "2024-05-12"

[build]
command = "pnpm build"
output_dir = "dist"

[build.upload]
format = "directory"

# Explicit routing configuration removed - Worker handles /s/* directly via route

# SPA fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[observability.logs]
enabled = true