name = "protosnap-worker"
main = "apps/worker/src/index.ts"
compatibility_date = "2024-05-12"

[[kv_namespaces]]
binding = "KV_USERS"
id = "REPLACE_WITH_KV_USERS_ID"

[[kv_namespaces]]
binding = "KV_SNAPS"
id = "REPLACE_WITH_KV_SNAPS_ID"

[[r2_buckets]]
binding = "R2_SNAPSHOTS"
bucket_name = "protosnap-snapshots"

[[durable_objects.bindings]]
name = "COMMENTS_DO"
class_name = "CommentsRoom"

[[migrations]]
tag = "v1"
new_classes = ["CommentsRoom"]

[build]
command = "" # tsc via packages
cwd = "../" # project root

[triggers]
crons = ["0 4 * * *"]

[vars]
SESSION_HMAC_SECRET = "REPLACE_WITH_RANDOM_BASE64"
R2_ACCOUNT_ID = "REPLACE_WITH_ACCOUNT_ID"
R2_ACCESS_KEY_ID = "REPLACE_WITH_ACCESS_KEY"
R2_SECRET_ACCESS_KEY = "REPLACE_WITH_SECRET"
TURNSTILE_SECRET_KEY = "REPLACE_WITH_TURNSTILE_SECRET"
PUBLIC_BASE_URL = "https://quickstage.tech"
LICENSE_BYPASS_KEY = "REPLACE_WITH_DEV_LICENSE_KEY"
REQUIRE_LICENSE = "false"
RP_ID = "quickstage.tech"
STRIPE_SECRET_KEY = "sk_live_..."
STRIPE_PRICE_ID = "price_..."
STRIPE_WEBHOOK_SECRET = "whsec_..."

