name = "quickstage-worker"
main = "../apps/worker/src/index.ts"
compatibility_date = "2024-05-12"

# Stripe configuration
[vars]
# STRIPE_PRICE_ID = "price_1RuSJcPDkQopAc5hGO0qLNvU"  # TESTING Your $6/mo price ID 
# STRIPE_ANNUAL_PRICE_ID = "price_1S1WrMPDkQopAc5hDDKEpr5c"  # TESTING Your $60/year price ID
STRIPE_PRICE_ID = "price_1S1Z9bAokLtL9KQyOghFAgda"  # Your production $6/mo price ID
STRIPE_ANNUAL_PRICE_ID = "price_1S1Z9bAokLtL9KQydC9VIcE2"  # Your production $60/year price ID
PUBLIC_BASE_URL = "https://quickstage.tech"  # Base URL for Stripe success/cancel redirects

# Secrets (set these by running the below commands and doing the input when prompted)
# wrangler secret put STRIPE_SECRET_KEY --config ../../infra/wrangler.toml
# wrangler secret put STRIPE_WEBHOOK_SECRET --config ../../infra/wrangler.toml
# wrangler secret put OPENAI_API_KEY --config ../../infra/wrangler.toml

# Custom domain for clean snapshot URLs
[triggers.custom_domains]
domain = "snap.quickstage.tech"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

# Routes for clean URLs on main domain - all Worker endpoints
[[routes]]
pattern = "quickstage.tech/api/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/s/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/analytics/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/auth/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/billing/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/debug/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/me"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/snapshots/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/tokens/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/admin/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/webhooks/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/extensions/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/comments/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/upload-url"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/upload"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6"

[[routes]]
pattern = "quickstage.tech/snap/*"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6" 

[[kv_namespaces]]
binding = "KV_USERS"
id = "2808162d18d0411d9b05ab8ae76fa500"

[[kv_namespaces]]
binding = "KV_SNAPS"
id = "9480e24f0477412ea9500030f599e16b"

[[kv_namespaces]]
binding = "KV_ANALYTICS"
id = "a44c5d74f9dd42b3aa378f45e19fb5ba"

[[kv_namespaces]]
binding = "KV_PROJECTS"
id = "f29d8835783746e187e78fc20bc668fe"

[[kv_namespaces]]
binding = "KV_NOTIFICATIONS"
id = "c4d22c0124d842168ec5647c999d81e2"

[[kv_namespaces]]
binding = "KV_SUBSCRIPTIONS"
id = "0e418bc8c6104af7b27c709dcca65d64"

[[kv_namespaces]]
binding = "KV_REVIEWS"
id = "1126b1fb44e7460f9eed0d3a342cf685"

[[r2_buckets]]
binding = "R2_SNAPSHOTS"
bucket_name = "snapshots"

[[durable_objects.bindings]]
name = "COMMENTS_DO"
class_name = "CommentsRoom"
id = "f1542cc2d727402283b87219b199b013"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CommentsRoom"]

[build]
command = "" # tsc via packages
cwd = "../" # project root

[triggers]
crons = ["0 4 * * *"]

[observability.logs]
enabled = true