name = "quickstage-worker"
main = "../apps/worker/src/index.ts"
compatibility_date = "2024-05-12"

[[kv_namespaces]]
binding = "KV_USERS"
id = "2808162d18d0411d9b05ab8ae76fa500"

[[kv_namespaces]]
binding = "KV_SNAPS"
id = "9480e24f0477412ea9500030f599e16b"

[[r2_buckets]]
binding = "R2_SNAPSHOTS"
bucket_name = "snapshots"

[[durable_objects.bindings]]
name = "COMMENTS_DO"
class_name = "CommentsRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CommentsRoom"]

[build]
command = "" # tsc via packages
cwd = "../" # project root

[triggers]
crons = ["0 4 * * *"]

[vars]
R2_ACCOUNT_ID = "518ca8e15f53365e91b4405317cb7772"
PUBLIC_BASE_URL = "https://quickstage.tech"
LICENSE_BYPASS_KEY = "dev-bypass-key"
REQUIRE_LICENSE = "false"
RP_ID = "quickstage.tech"
STRIPE_PRICE_ID = "price_1RuSJcPDkQopAc5hGO0qLNvU"

