name = "quickstage-worker"
main = "../apps/worker/src/index.ts"
compatibility_date = "2024-05-12"

# Stripe configuration
[vars]
STRIPE_PRICE_ID = "price_1RuSJcPDkQopAc5hGO0qLNvU"  # Your $6/mo price ID

# Stripe secrets (set these with: wrangler secret put STRIPE_SECRET_KEY)
# wrangler secret put STRIPE_SECRET_KEY
# wrangler secret put STRIPE_WEBHOOK_SECRET

# Custom domain for clean snapshot URLs
[triggers.custom_domains]
domain = "snap.quickstage.tech"
zone_id = "b8c62b949012c4a1f5497fe2cd85d6b6" 

[[kv_namespaces]]
binding = "KV_USERS"
id = "2808162d18d0411d9b05ab8ae76fa500"

[[kv_namespaces]]
binding = "KV_SNAPS"
id = "9480e24f0477412ea9500030f599e16b"

[[kv_namespaces]]
binding = "KV_ANALYTICS"
id = "a44c5d74f9dd42b3aa378f45e19fb5ba"

[[r2_buckets]]
binding = "R2_SNAPSHOTS"
bucket_name = "snapshots"

[[durable_objects.bindings]]
name = "COMMENTS_DO"
class_name = "CommentsRoom"
id = "f1542cc2d727402283b87219b199b013"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CommentsRoom"]

[build]
command = "" # tsc via packages
cwd = "../" # project root

[triggers]
crons = ["0 4 * * *"]

[observability.logs]
enabled = true