// Auto-generated by release workflow
export const EXTENSION_VERSION = '0.0.13';
export const EXTENSION_DOWNLOAD_URL = '/quickstage.vsix';
export const EXTENSION_VERSIONED_URL = '/quickstage-0.0.13.vsix';
export const EXTENSION_CHECK_URL = '/api/extensions/version';
export const EXTENSION_BUILD_TIME = '2025-08-13T04:50:13.548Z';
