// Auto-generated by release workflow
export const EXTENSION_VERSION = '0.0.6';
export const EXTENSION_DOWNLOAD_URL = '/quickstage.vsix';
export const EXTENSION_CHECK_URL = '/api/extensions/version';
